port: 3000
client: http://localhost:5173
salt: 10

jwt:
  secret-key: hehe
  access-token-expire-in: 1h
  refresh-token-expire-in: 3d

facebook:
  client-id: 1213240936224087
  client-secret: c5eb7ba9c91525de7e980e1d15786555
  graph-url: https://graph.facebook.com

postgres:
  username: postgres
  password: vmnvmn3110
  name: postgres
  host: localhost
  port: 5432
  dialect: postgres

cloudinary:
  cloud-name: dzd6xmzvv
  api-key: 156269933569375
  api-secret: 3f_Nhoy9S7uk_sJuUQyYBD0pGkQ

redis:
  url: redis://127.0.0.1:6379
  host: 127.0.0.1
  port: 6379

google:
  client-id: 437786877308-s7bfl5kvrc9ne92o94o5v1ikng7h6pjj.apps.googleusercontent.com
  client-secret: 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
  token: 1//04kzqaW_QruhnCgYIARAAGAQSNwF-L9Irp61ynMgS5o-CEJ5KAgn7m8WIErtUxaF0KCp8b8_j3GZEYF4eK0wiQWY9yqsiXtKk7M4
  oauth2-callback-url: https://developers.google.com/oauthplayground

otp:
  ttl: 5m
  refresh-otp-time: 3m
